name: hapi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  carousel_slider: 4.2.1
  heroicons: 0.8.0
  intl: 0.18.0
  flutter_svg: 2.0.4
  google_maps_flutter: 2.2.5
  custom_info_window: 1.0.1
  clippy_flutter: 1.1.1
  flutter_keyboard_visibility: 5.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  fonts: 
    - family: PlusJakartaSans
      fonts: 
        - asset: fonts/PlusJakartaSans-Regular.ttf
  uses-material-design: true

